version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
# re-direct to index.html if no path is give


- url: /
  static_files: index.html
  upload: index.html

- url: /audio
  static_dir: audio

- url: /libraries
  static_dir: libraries

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /.*
  script: plase-dont-cry.app

libraries:
- name: webapp2
  version: latest
